services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "fetpamily"
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - database
volumes:
  postgres_data:

